# Tarpaulin Configuration
# Excludes test files from coverage analysis

[default]
# Exclude test files and directories from coverage
exclude-files = [
    "tests/*",
    "*_test.rs",
    "*_tests.rs",
    "*/tests/*",
    "*/test/*",
    "benches/*",
    "*/bench/*",
    "*/benchmark/*"
]

# Build options
skip-clean = true
engine = "Llvm"

# Test runner - use default cargo test since nextest isn't directly supported
# but we still get LLVM engine benefits

# Parallel test execution
parallel = true

# Number of parallel jobs (adjust based on CPU cores)
jobs = 4

# Timeout for tests
timeout = "5m"

# Follow child processes
follow-exec = false

# Don't count lines with only closing braces
avoid-cfg-tarpaulin = true

# Include test functions in coverage to track what they call
include-tests = true

# Output formats
out = ["Html", "Json", "Lcov"]

# Output directory
output-dir = "target/coverage"