# Memento Mori Configuration

# Default Claude command options
[claude]
default_args = ["--no-preamble"]

# Custom commands for different stages
[commands]
# Implementation phase
implement = "/implement-spec"
# Linting phase
lint = "/lint"
# Testing phase
test = "/test"
# Review phase
review = "/review"

# Command templates
[templates]
implement = """
Please implement the following specification:

Spec: {spec_name}
Iteration: {iteration}

{spec_content}

Focus on:
1. Meeting all acceptance criteria
2. Writing clean, maintainable code
3. Following best practices
"""

lint = """
Please run linting checks on the current implementation for:

Spec: {spec_name}

{spec_content}

Check for:
1. Code style violations
2. Potential bugs
3. Performance issues
4. Security concerns
"""

test = """
Please create and run tests for:

Spec: {spec_name}

{spec_content}

Ensure:
1. All acceptance criteria are tested
2. Edge cases are covered
3. Tests are maintainable
"""

review = """
Please review the implementation for:

Spec: {spec_name}

{spec_content}

Current state:
- Iteration: {iteration}
- Previous feedback addressed: {completed}

If everything looks good, respond with 'COMPLETED: <summary>'.
Otherwise, provide specific feedback for improvement.
"""