# Security-focused workflow
# Analyzes code for security issues and applies fixes
- claude: "/prodigy-security-audit"
  id: audit
  outputs:
    spec:
      file_pattern: "specs/temp/*-security.md"

- claude: "/prodigy-implement-spec ${audit.spec}"

- claude: "/prodigy-security-validate"