name: feature-development
description: Complete feature development workflow  
version: 1.0.0

triggers:
  - type: spec_added
    filter: "specs/features/*.md"
  - type: manual

parameters:
  review_required:
    type: boolean
    default: true
    description: Whether human review is required
  
  parallel_implementation:
    type: boolean  
    default: false
    description: Run implementation steps in parallel

stages:
  - name: planning
    steps:
      - name: analyze-requirements
        command: mmm claude run --command analyze --args "{{ spec_id }}"
        on_failure: retry
        max_retries: 2
        
      - name: estimate-complexity
        command: mmm claude run --command estimate --args "{{ spec_id }}"
        outputs:
          - complexity_score
          - estimated_hours

  - name: implementation
    condition: "{{ outputs.complexity_score }} < 10"
    steps:
      - name: implement-feature
        command: mmm claude run --command implement --args "{{ spec_id }}"
        
      - name: run-tests
        command: cargo test
        on_failure: 
          command: mmm claude run --command fix-tests
          retry: 3

  - name: review
    condition: "{{ parameters.review_required }}"
    steps:
      - name: code-review
        command: mmm claude run --command review --args "{{ spec_id }}"
        outputs:
          - review_result
          
      - name: human-checkpoint
        type: checkpoint
        message: "Please review the implementation and test results"
        timeout: 24h

  - name: finalization
    steps:
      - name: update-documentation
        command: mmm claude run --command update-docs --args "{{ spec_id }}"
        
      - name: mark-complete
        command: mmm spec complete "{{ spec_id }}"

on_success:
  - type: notification
    message: "Feature {{ spec_id }} completed successfully!"

on_failure:
  - type: notification
    message: "Workflow failed for {{ spec_id }} at stage: {{ failed_stage }}"