# Iterative refinement workflow
# Uses multiple review-implement cycles for gradual improvement

commands = [
    "mmm-code-review --focus architecture",
    "mmm-implement-spec",
    "mmm-code-review --focus error-handling",
    "mmm-implement-spec",
    "mmm-code-review --focus performance",
    "mmm-implement-spec",
    "mmm-code-review --focus testing",
    "mmm-implement-spec",
    "mmm-lint"
]

max_iterations = 2

# This workflow uses focused reviews:
# 1. Architecture improvements
# 2. Error handling enhancements
# 3. Performance optimizations
# 4. Testing improvements
# 5. Final quality check
#
# Each iteration addresses all focus areas
# Lower iteration count since each pass is comprehensive