# Quick fix workflow
# Minimal workflow for fast improvements

commands = [
    "mmm-code-review --focus critical",
    "mmm-implement-spec",
    "mmm-lint"
]

max_iterations = 3

# This minimal workflow:
# 1. Reviews only critical issues
# 2. Implements fixes
# 3. Validates with linting
#
# Perfect for quick improvements or CI/CD pipelines