# Refactoring-focused workflow
# Improves code structure and maintainability

commands = [
    "mmm-refactor",
    "mmm-implement-spec",
    "mmm-test-generate",
    "mmm-implement-spec",
    "mmm-lint"
]

max_iterations = 5

# This workflow:
# 1. Identifies refactoring opportunities
# 2. Implements the refactoring
# 3. Generates tests for refactored code
# 4. Implements the tests
# 5. Ensures code quality with linting