# Security-focused workflow
# Analyzes code for security issues and applies fixes
commands:
    - name: mmm-security-audit
      id: audit
      outputs:
        spec:
          file_pattern: "specs/temp/*-security.md"
    
    - name: mmm-implement-spec
      inputs:
        spec:
          from: "${audit.spec}"
          pass_as:
            argument:
              position: 0
    
    - name: mmm-security-validate