# Security-focused workflow
# Identifies and fixes security vulnerabilities

commands = [
    "mmm-security-audit",
    "mmm-implement-spec",
    "mmm-test-generate --security",
    "mmm-implement-spec",
    "mmm-lint"
]

max_iterations = 8

# This workflow:
# 1. Performs security audit
# 2. Implements security fixes
# 3. Generates security-focused tests
# 4. Implements the security tests
# 5. Validates with linting
#
# Higher iteration count for thorough security review