# Security-focused workflow
# Analyzes code for security issues and applies fixes
commands:
    - claude: "/mmm-security-audit"
      id: audit
      outputs:
        spec:
          file_pattern: "specs/temp/*-security.md"
    
    - claude: "/mmm-implement-spec ${audit.spec}"
      inputs:
        spec:
          from: "${audit.spec}"
          pass_as:
            argument:
              position: 0
    
    - claude: "/mmm-security-validate"