# Test-driven development workflow
# Generates tests first, then ensures code meets test requirements

commands = [
    "mmm-test-generate",
    "mmm-implement-spec",
    "mmm-coverage",
    "mmm-code-review --focus testing",
    "mmm-implement-spec",
    "mmm-lint"
]

max_iterations = 7

# This workflow:
# 1. Generates comprehensive tests
# 2. Implements the tests
# 3. Checks test coverage
# 4. Reviews code for testability
# 5. Implements testability improvements
# 6. Final quality check