# Project-specific MMM Configuration

[project]
name = "memento-mori"
description = "A Rust CLI tool for implementing self-sufficient loops with Claude CLI"
version = "0.1.0"

# Override global defaults for this project
[defaults]
claude_model = "claude-3-sonnet-20240229"
claude_max_tokens = 8192
workflow_timeout = 7200  # 2 hours for this project

# Project-specific paths
[paths]
specs = "specs/"
templates = "templates/"
state_db = ".mmm/state.db"

# Custom commands for this project
[commands]
build = "cargo build"
test = "cargo test"
lint = "cargo clippy -- -D warnings"
fmt = "cargo fmt --check"

# Workflow configuration
[workflow]
# Default workflow for specs
default_template = "implement-feature.yaml"
# Auto-checkpoint on these events
checkpoint_on = ["test_pass", "lint_pass", "iteration_complete"]

# Project health checks
[health]
required_files = [
    "Cargo.toml",
    "src/main.rs",
    ".mmm/PROJECT.md"
]
required_commands = ["cargo", "git"]

# Integration settings
[integrations]
# Git integration
git_auto_commit = false
git_branch_prefix = "mmm/"

# Claude CLI settings  
claude_cli_path = "claude"
claude_cli_flags = ["--no-preamble", "--dangerously-skip-permissions"]
