[book]
title = "Prodigy Documentation"
authors = ["Prodigy Contributors"]
description = "AI-powered workflow orchestration for development teams"
src = "src"
language = "en"

[build]
build-dir = "output"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/gbaker-prodigy/prodigy"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/gbaker-prodigy/prodigy/edit/main/book/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = true
