name: Code Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Generate code coverage
      run: just coverage
      env:
        PRODIGY_TEST_MODE: "true"

    - name: Archive code coverage results
      uses: actions/upload-artifact@v5
      with:
        name: code-coverage-report
        path: target/coverage/

    - name: Check coverage threshold
      run: just coverage-check
      env:
        PRODIGY_TEST_MODE: "true"
